/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import ShopifyBuy from 'react-native-shopify-buy';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    ShopifyBuy.initialize('magrinj.myshopify.com', '06245c55e4fa977ac0de4163c0d181b4', 'fr-FR');

    ShopifyBuy.creditCardVault({
      firstName: 'Bob',
      lastName: 'Norman',
      number: '4242424242424242',
      expiryMonth: '12',
      expiryYear: '2021',
      verificationCode: '123'
    }).then((token) => {
      console.log('TOKEN: ', token);
    }).catch((err) => {
      console.log('ERROR: ', err);
    })
    // RNShopifyBuy.test();
    /* RNShopifyBuy.sampleMethod('Testing', 123, (message) => {
      this.setState({
        status: 'native callback received',
        message
      });
    }); */
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNShopifyBuy example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
